"""Project scaffolder — writes generated projects to real directories.

Turns a structured file map (or an LLM's JSON output) into an actual project
tree under ``generated/`` with path-traversal protection, then optionally runs
it in the sandbox. This is the layer that makes "build me an app" produce
real files instead of only text.
"""

import json
import re
import shutil
from pathlib import Path


class ProjectScaffolder:
    """Writes a dict of {relative_path: content} into a project directory."""

    def __init__(self, base_dir: str = None):
        self.base_dir = Path(
            base_dir or (Path(__file__).resolve().parent.parent / "generated")
        )
        self.base_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _safe_path(base: Path, rel: str) -> Path:
        """Resolve a relative path under base, rejecting traversal escapes."""
        rel = str(rel).replace("\\", "/").lstrip("/")
        if not rel or rel in (".", ".."):
            raise ValueError(f"invalid relative path: {rel!r}")
        target = (base / rel).resolve()
        if not target.is_relative_to(base.resolve()):
            raise ValueError(f"path escapes base directory: {rel!r}")
        return target

    def scaffold(self, project: str, files: dict, overwrite: bool = True) -> dict:
        """Write {relative_path: content} into generated/<project>/."""
        project = self._slug(project) or "untitled"
        root = self.base_dir / project
        root.mkdir(parents=True, exist_ok=True)
        written, errors = [], []
        for rel, content in (files or {}).items():
            try:
                target = self._safe_path(root, rel)
                if target.exists() and not overwrite:
                    raise FileExistsError(f"already exists: {rel}")
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(str(content), encoding="utf-8")
                written.append(str(target.relative_to(root)).replace("\\", "/"))
            except Exception as exc:  # noqa: BLE001
                errors.append({"path": rel, "error": str(exc)})
        return {
            "ok": not errors,
            "project": project,
            "root": str(root),
            "files": written,
            "file_count": len(written),
            "errors": errors,
        }

    @staticmethod
    def extract_json_block(text: str) -> dict:
        """Pull the first JSON object out of an LLM response.

        Uses ``JSONDecoder.raw_decode`` to walk the string, so it tolerates
        prose, markdown fences and multiple JSON values (returns the first).
        """
        if not text:
            return {}
        decoder = json.JSONDecoder()
        pos = 0
        length = len(text)
        while pos < length:
            ch = text[pos]
            if ch not in "{[":
                pos += 1
                continue
            try:
                obj, end = decoder.raw_decode(text, pos)
            except (json.JSONDecodeError, ValueError):
                pos += 1
                continue
            if isinstance(obj, dict):
                return obj
            return {}
        return {}

    def scaffold_from_json(self, text: str, project: str, overwrite: bool = True) -> dict:
        """Scaffold from an LLM response containing a ``{"files": {...}}`` map.

        Also accepts a flat {path: content} map. Returns an error dict (never
        raises) when no usable file map is found.
        """
        data = self.extract_json_block(text)
        if not data:
            return {"ok": False, "error": "no JSON object found in response"}
        files = data.get("files")
        if isinstance(files, dict) and files:
            return self.scaffold(project, files, overwrite=overwrite)
        if "files" not in data and any(
            isinstance(data[k], str) for k in data
        ):
            return self.scaffold(project, data, overwrite=overwrite)
        return {"ok": False, "error": "no 'files' map found in JSON"}

    @staticmethod
    def default_project(description: str, project: str) -> dict:
        """Deterministic fallback project when the LLM returns nothing parseable."""
        name = ProjectScaffolder._slug(project) or "untitled"
        return {
            "README.md": (
                f"# {name}\n\n{description.strip()}\n\n"
                "Generated by Dutchkem Model 4.0.\n"
            ),
            "requirements.txt": "requests>=2.31.0\n",
            "app.py": (
                "import os\n"
                "\n"
                "def main():\n"
                f"    print('Hello from {name}!')\n"
                "\n"
                "if __name__ == '__main__':\n"
                "    main()\n"
            ),
        }

    @staticmethod
    def _slug(name: str) -> str:
        return re.sub(r"[^A-Za-z0-9._-]+", "_", (name or "").strip())

    def list(self, project: str = None) -> dict:
        """List generated projects, or all files within a single project."""
        if project:
            root = self.base_dir / self._slug(project)
            if not root.exists():
                return {"project": project, "error": "not found"}
            files = [
                str(p.relative_to(root)).replace("\\", "/")
                for p in root.rglob("*")
                if p.is_file()
            ]
            return {"project": project, "root": str(root), "files": files}
        dirs = sorted(p.name for p in self.base_dir.iterdir() if p.is_dir())
        return {"projects": dirs, "root": str(self.base_dir)}

    def read(self, project: str, path: str) -> dict:
        """Read a single file from a generated project."""
        root = self.base_dir / self._slug(project)
        try:
            target = self._safe_path(root, path)
        except ValueError as exc:
            return {"ok": False, "error": str(exc)}
        if not target.exists():
            return {"ok": False, "error": f"file not found: {path}"}
        return {"ok": True, "path": path, "content": target.read_text(encoding="utf-8")}

    def remove(self, project: str) -> dict:
        """Delete a generated project directory."""
        root = self.base_dir / self._slug(project)
        if not root.exists():
            return {"ok": False, "error": f"project '{project}' not found"}
        shutil.rmtree(root)
        return {"ok": True, "removed": project}
